# Generated by Django 5.0 on 2024-01-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cobros',
            fields=[
                ('ID_COBROS', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NUMERO_DE_RECIBO', models.CharField(max_length=5)),
                ('CODIGO_INTEGRANTE', models.CharField(max_length=9)),
                ('APELLIDO_PATERNO', models.TextField(max_length=20)),
                ('APELLIDO_MATERNO', models.TextField(max_length=20)),
                ('NOMBRES', models.TextField(max_length=20)),
                ('CODIGO_DE_GRUPO_INTEGRANTES', models.CharField(max_length=5)),
                ('FECHA_EMICION_RECIBO', models.DateTimeField(auto_now_add=True)),
                ('FECHA_VENCIMIENTO_RECIBO', models.DateField()),
                ('MONEDA_A_PAGAR', models.CharField(max_length=6)),
                ('CODIGO_REFERENCIA_CLIENTE', models.CharField(max_length=5)),
                ('DESCRIPCION_COBRO_REALIZAR', models.TextField(max_length=200)),
                ('OBSERVACIONES_RECIBO', models.TextField(max_length=200)),
                ('INDICADOR_COBRO_MORA', models.CharField(max_length=1)),
                ('CODIGO_CONCEPTO_1', models.CharField(max_length=1)),
                ('IMPORTE_COBRO_CONCEPTO_1', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DataConsolidado',
            fields=[
                ('ID_DATOS', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ITEM', models.IntegerField(unique=True)),
                ('CODIGO_DE_PAGO', models.IntegerField(unique=True)),
                ('MZLTS', models.CharField(max_length=5)),
                ('CAPTACION', models.DateField()),
                ('ASESOR', models.TextField(max_length=200)),
                ('APELLIDO_PATERNO', models.TextField(max_length=200)),
                ('APELLIDO_MATERNO', models.TextField(max_length=200)),
                ('NOMBRES', models.TextField(max_length=20)),
                ('DOC', models.CharField(max_length=4, unique=True)),
                ('NUMERO', models.CharField(max_length=8, unique=True)),
                ('DIRECCION', models.CharField(max_length=100)),
                ('DISTRITO', models.TextField(max_length=100)),
                ('PROVINCIA', models.TextField(max_length=100)),
                ('DEPARTAMENTO', models.TextField(max_length=100)),
                ('CELULAR', models.CharField(max_length=12, unique=True)),
                ('EMAIL', models.CharField(max_length=30, unique=True)),
                ('M2', models.CharField(max_length=8)),
                ('UBICACION', models.TextField()),
                ('PRECIOVENTA', models.CharField()),
                ('INICIAL', models.CharField()),
                ('SALDO', models.CharField()),
                ('COUTAS', models.IntegerField(max_length=2)),
                ('COUTA', models.CharField()),
                ('INICIO_PAGO', models.DateField()),
                ('CVENCIDAS', models.IntegerField()),
                ('CPAGADAS', models.IntegerField()),
                ('SVENCIDOS', models.CharField()),
                ('SPAGADOS', models.CharField()),
                ('COMENTARIO', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recaudaciones',
            fields=[
                ('ID_RECAUDACIONES', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('NUMERO_DE_RECIBO', models.CharField(max_length=100000)),
                ('CODIGO_INTEGRANTE', models.CharField(max_length=9)),
                ('APELLIDOS_NOMBRES', models.TextField(max_length=40)),
                ('GRUPO', models.CharField(max_length=10)),
                ('DESCRIPCION_RECIBO', models.CharField(max_length=40)),
                ('IMP_RECIBO', models.CharField()),
                ('FECHA_VENCIMIENTO', models.DateField()),
                ('DIA_MORA', models.IntegerField(max_length=1)),
                ('IMP_MORA', models.CharField()),
                ('IMP_TOTAL', models.CharField()),
                ('FECHA_PAGO', models.DateField()),
                ('MZLTE', models.CharField(max_length=5)),
                ('FORMA_PAGO', models.TextField()),
                ('CALC_MORA', models.CharField(verbose_name=2)),
                ('FECHA_ACTUALIZADA', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Resumen',
            fields=[
                ('ID_RESUMEN', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ID_INTEGRANTE', models.CharField()),
                ('FECHA_RESUMEN', models.DateField()),
                ('CVENCIDAS', models.IntegerField()),
                ('CPAGADAS', models.IntegerField()),
                ('SVENCIDOS', models.CharField()),
                ('SPAGADOS', models.CharField()),
            ],
        ),
    ]
