# Generated by Django 5.0 on 2024-01-10 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobros',
            name='CODIGO_INTEGRANTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estadosdecuenta.dataconsolidado'),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='CODIGO_INTEGRANTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estadosdecuenta.dataconsolidado'),
        ),
    ]
