# Generated by Django 5.0 on 2024-01-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0002_alter_cobros_codigo_integrante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconsolidado',
            name='CELULAR',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='NUMERO',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
