# Generated by Django 5.0 on 2024-01-11 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0004_alter_dataconsolidado_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconsolidado',
            name='APELLIDO_MATERNO',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='APELLIDO_PATERNO',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='ASESOR',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='CAPTACION',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='CELULAR',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='CODIGO_DE_PAGO',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='COMENTARIO',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='COUTA',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='COUTAS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='CPAGADAS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='CVENCIDAS',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='DEPARTAMENTO',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='DIRECCION',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='DISTRITO',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='DOC',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='EMAIL',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='INICIAL',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='INICIO_PAGO',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='M2',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='MZLTS',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='NOMBRES',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='NUMERO',
            field=models.CharField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='PRECIOVENTA',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='PROVINCIA',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='SALDO',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='SPAGADOS',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='SVENCIDOS',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='UBICACION',
            field=models.TextField(null=True),
        ),
    ]
