# Generated by Django 5.0 on 2024-01-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0005_alter_dataconsolidado_apellido_materno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataconsolidado',
            old_name='INICIO_PAGO',
            new_name='INICIOPAGO',
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='APELLIDO_MATERNO',
            field=models.TextField(db_column='APELLIDO MATERNO', null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='APELLIDO_PATERNO',
            field=models.TextField(db_column='APELLIDO PATERNO', null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='CODIGO_DE_PAGO',
            field=models.IntegerField(db_column='CÓDIGO DE PAGO', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='DIRECCION',
            field=models.CharField(db_column='DIRECCIÓN', null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='ID_DATOS',
            field=models.CharField(db_column='IDDATOS', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='NUMERO',
            field=models.CharField(db_column='NÚMERO', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='UBICACION',
            field=models.TextField(db_column='UBICACIÓN', null=True),
        ),
    ]
