# Generated by Django 5.0 on 2024-01-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0006_rename_inicio_pago_dataconsolidado_iniciopago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconsolidado',
            name='CELULAR',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='DOC',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='EMAIL',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='NUMERO',
            field=models.CharField(db_column='NÚMERO', null=True),
        ),
    ]
