# Generated by Django 5.0 on 2024-01-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0007_alter_dataconsolidado_celular_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataconsolidado',
            name='ITEM',
            field=models.IntegerField(),
        ),
    ]
