# Generated by Django 5.0 on 2024-01-11 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0009_alter_dataconsolidado_codigo_de_pago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataconsolidado',
            old_name='COUTA',
            new_name='CUOTA',
        ),
        migrations.RenameField(
            model_name='dataconsolidado',
            old_name='COUTAS',
            new_name='CUOTAS',
        ),
    ]
