# Generated by Django 5.0 on 2024-01-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0012_alter_cobros_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobros',
            name='APELLIDO_MATERNO',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='APELLIDO_PATERNO',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='CODIGO_CONCEPTO_1',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='CODIGO_DE_GRUPO_INTEGRANTES',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='CODIGO_REFERENCIA_CLIENTE',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='DESCRIPCION_COBRO_REALIZAR',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='ID_COBROS',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='IMPORTE_COBRO_CONCEPTO_1',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='INDICADOR_COBRO_MORA',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='MONEDA_A_PAGAR',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='NOMBRES',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='NUMERO_DE_RECIBO',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='OBSERVACIONES_RECIBO',
            field=models.TextField(null=True),
        ),
    ]
