# Generated by Django 5.0 on 2024-01-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0013_alter_cobros_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobros',
            name='CODIGO_INTEGRANTE',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='CODIGO_DE_PAGO',
            field=models.CharField(db_column='CÓDIGO DE PAGO', null=True, unique=True),
        ),
    ]
