# Generated by Django 5.0 on 2024-01-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0014_alter_cobros_codigo_integrante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recaudaciones',
            name='APELLIDOS_NOMBRES',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='CALC_MORA',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='CODIGO_INTEGRANTE',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='DESCRIPCION_RECIBO',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='DIA_MORA',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='FECHA_ACTUALIZADA',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='FECHA_PAGO',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='FECHA_VENCIMIENTO',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='FORMA_PAGO',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='GRUPO',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='ID_RECAUDACIONES',
            field=models.CharField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='IMP_MORA',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='IMP_RECIBO',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='IMP_TOTAL',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='MZLTE',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='NUMERO_DE_RECIBO',
            field=models.CharField(null=True),
        ),
    ]
