# Generated by Django 5.0 on 2024-01-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0016_alter_recaudaciones_codigo_integrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobros',
            name='CODIGO_INTEGRANTE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estadosdecuenta.dataconsolidado'),
        ),
    ]
