# Generated by Django 5.0 on 2024-01-13 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0017_alter_cobros_codigo_integrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobros',
            name='CODIGO_INTEGRANTE',
            field=models.ForeignKey(db_column='CODIGO_INTEGRANTE', null=True, on_delete=django.db.models.deletion.CASCADE, to='estadosdecuenta.dataconsolidado'),
        ),
    ]
