# Generated by Django 5.0 on 2024-01-13 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0018_alter_cobros_codigo_integrante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobros',
            name='CODIGO_INTEGRANTE',
        ),
        migrations.AddField(
            model_name='cobros',
            name='CODIGO_INTEGRANTE_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estadosdecuenta.dataconsolidado'),
        ),
    ]
