# Generated by Django 5.0 on 2024-01-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0022_alter_recaudaciones_codigo_integrante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobros',
            name='CODIGO_INTEGRANTE',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='CODIGO_INTEGRANTE',
            field=models.CharField(null=True),
        ),
    ]
