# Generated by Django 5.0 on 2024-01-16 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0024_cobros_codigo_de_pago_recaudaciones_codigo_de_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobros',
            name='CODIGO_DE_PAGO',
            field=models.ForeignKey(blank=True, db_column='CODIGO DE PAGO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estadosdecuenta.dataconsolidado'),
        ),
        migrations.AlterField(
            model_name='dataconsolidado',
            name='CODIGO_DE_PAGO',
            field=models.CharField(db_column='CODIGO DE PAGO', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='recaudaciones',
            name='CODIGO_DE_PAGO',
            field=models.ForeignKey(blank=True, db_column='CODIGO DE PAGO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='estadosdecuenta.dataconsolidado'),
        ),
    ]
