# Generated by Django 5.0 on 2024-01-16 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0025_alter_cobros_codigo_de_pago_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobros',
            name='CODIGO_DE_PAGO',
        ),
        migrations.RemoveField(
            model_name='recaudaciones',
            name='CODIGO_DE_PAGO',
        ),
    ]
