# Generated by Django 5.0 on 2024-01-17 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0026_remove_cobros_codigo_de_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobros',
            name='IMPORTE_COBRO_COMPLETO',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='cobros',
            name='FECHA_EMICION_RECIBO',
            field=models.DateTimeField(),
        ),
    ]
