# Generated by Django 5.0 on 2024-01-19 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estadosdecuenta', '0027_cobros_importe_cobro_completo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobros',
            name='IMPORTE_COBRO_CONCEPTO_1',
        ),
    ]
